if: (branch = master) OR (type = pull_request) OR (tag IS present)
language: ruby
services:
- docker
env:
  global:
    - DOCKER_TAG=validation-worker
before_install:
- openssl aes-256-cbc -K $encrypted_fd47d756d2b5_key -iv $encrypted_fd47d756d2b5_iv
  -in id_rsa_worker.enc -out ~/id_rsa_worker -d
- |
  # Create variables.sh, it represents a text file database, will be used for test purposes
  mkdir -p /tmp/volume
  touch /tmp/volume/variables.sh
  echo "KEY_GITTER_TRUSTED_SETUP_ROOM=$KEY_GITTER_TRUSTED_SETUP_ROOM" >> /tmp/volume/variables.sh
  echo "THRESHOLD_DATE_FOR_FILE_ACCEPTANCE=20190404122952" >> /tmp/volume/variables.sh
  echo "TRUSTED_SETUP_TURN=2" >> /tmp/volume/variables.sh
  echo "SFTP_ADDRESS=trusted-setup.staging.gnosisdev.com" >> /tmp/volume/variables.sh
  echo "MAKE_FIRST_CONTRIBUTION=yes" >> /tmp/volume/variables.sh
  echo "CONSTRAINED=true" >> /tmp/volume/variables.sh
  echo "SSH_USER=validationworker" >> /tmp/volume/variables.sh
  echo "CHALLENGE_WORKDIR=/tmp" >> /tmp/volume/variables.sh
  echo "DATABASE_FILE_PATH=/tmp/volume/variables.sh" >> /tmp/volume/variables.sh # /app/variables.sh will get updated by some scripts
  echo "RUST_BACKTRACE=1" >> /tmp/volume/variables.sh
  echo "GITTER_ACCESS_TOKEN=$GITTER_ACCESS_TOKEN" >> /tmp/volume/variables.sh
  echo "GITTER_ROOM=5ca22b42d73408ce4fbc758e" >> /tmp/volume/variables.sh
- chmod 600 ~/id_rsa_worker
install:
  - docker build -t $DOCKER_TAG -f DockerfileDevops .
script:
- docker run -it -v ~/id_rsa_worker:/root/.ssh/id_rsa_worker --env-file /tmp/volume/variables.sh -v /tmp/volume:/tmp/volume $DOCKER_TAG
  bash -c "bash test/util/run_all_tests.sh"
after_script:
- |
  # Create Docker image if branch master and not on pull requests
  if [ "$TRAVIS_TEST_RESULT" == "0" ]; then
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "Pushing staging image...";
        docker tag $DOCKER_TAG gnosispm/$DOCKER_TAG:staging;
        docker push gnosispm/$DOCKER_TAG:staging;
        echo "The image has been pushed";
      elif [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
        echo "Pushing image tag $TRAVIS_TAG...";
        docker tag $DOCKER_TAG gnosispm/$DOCKER_TAG:$TRAVIS_TAG;
        docker push gnosispm/$DOCKER_TAG:$TRAVIS_TAG;
        echo "The image has been pushed";
      else
        echo "There's no need to push the image to Docker-hub";
      fi
    else
      echo "There's no need to push the image to Docker-hub";
    fi
  fi
